#!/usr/bin/env bash
# comment goes here.
file="school"

#if the file exists: school file exists
#if the file does not exist: school file does not exist
if [ -e $file ] 
then
  echo "$file file exists"

# if the file is empty: school file is empty
# if the file is not empty: school file is not empty
  if [ -s $file ] 
  then
    echo "$file file is not empty"
  else
    echo "$file file is empty"
  fi

# if the file is a regular file: school is a regular file
# if the file is not a regular file: (nothing)
  if [ -f $file ] 
  then
    echo "$file is a regular file"
  fi
else
  echo "$file file does not exist"
fi
